- name: install zsh
   portinstall: name=zsh state=present

 - name: default shell zsh
   shell: "chsh -s zsh"

 - name: install SUDO
   shell: "cd /usr/ports/security/sudo && make DISABLE_VULNERABILITIES=yes BATCH=yes install clean"

 - name: Add user to sudoers file
   lineinfile: "dest=/usr/local/etc/sudoers
               state=present
               regexp=''
               insertafter='EOF'
               line='michael ALL=(ALL) NOPASSWD: ALL'"
 
 - name: install oh-my-zsh
   shell: "curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh"..
